filter:
    excluded_paths: [vendor/*, ci/*, phpunit/*]

before_commands:
    - "composer install --prefer-source"

tools:
    php_cpd: true
    php_pdepend:
        excluded_dirs: [vendor, ci, phpunit]
    php_code_coverage:
        test_command: vendor/bin/phpunit -c phpunit/phpunit.xml