filter:
    excluded_paths: [vendor/*, ci/*, phpunit/*]

before_commands:
    - "composer install --prefer-source --no-dev"

tools:
    php_cpd: true
    php_pdepend:
        excluded_dirs: [vendor]
    php_code_coverage:
        test_command: phpunit -c phpunit/phpunit.xml